### ISSUE TITLE
The example app is failing on the latest version 4.0 on IOS and Android (Emulators and Physical)

### ISSUE THREAD

**Issue by rlueders** [sk3llo/ffmpeg_kit_flutter#113]
The example app is failing with the following errors when the hardware or software buttons are pressed. It happens on both Android and IOS and on both emulators and physical devices. 

I/flutter ( 5196): log: ffmpeg version n8.0
I/flutter ( 5196): log:  Copyright (c) 2000-2025 the FFmpeg developers
I/flutter ( 5196): log:
I/flutter ( 5196):
I/flutter ( 5196): log:   built with Android (13065274, +pgo, -bolt, +lto, -mlgo, based on r547379) clang version 20.0.0 (https://android.googlesource.com/toolchain/llvm-project b718bcaf8c198c82f3021447d943401e3ab5bd54)
I/flutter ( 5196):
I/flutter ( 5196): log:   configuration: --cross-prefix=aarch64-linux-android- --sysroot=/Users/me/Library/Android/sdk/ndk/29.0.13113456/toolchains/llvm/prebuilt/darwin-x86_64/sysroot --prefix=/Users/me/StudioProjects/ffmpeg-kit-6.0.LTS/prebuilt/android-arm64/ffmpeg --pkg-config=/opt/homebrew/bin/pkg-config --enable-version3 --arch=aarch64 --cpu=armv8-a --target-os=android --enable-neon --enable-asm --enable-inline-asm --ar=llvm-ar --cc=aarch64-linux-android24-clang --cxx=aarch64-linux-android24-clang++ --ranlib=llvm-ranlib --strip=llvm-strip --nm=llvm-nm --extra-libs='-L/Users/me/StudioProjects/ffmpeg-kit-6.0.LTS/prebuilt/android-arm64/cpu-features/lib -lndk_compat' --disable-autodetect --enable-cross-compile --enable-pic --enable-jni --enable-optimizations --enable-swscale --disable-static --enable-shared --enable-pthreads --enable-v4l2-m2m --disable-outdev=fbdev --disable-indev=fbdev --enable-small --disable-xmm-clobber-test --disable-debug --enable-lto --disable-neon-clobber-test --disable-programs --disable-doc --disable-
I/flutter ( 5196):
I/flutter ( 5196): log:   libavutil      60.  8.100 / 60.  8.100
I/flutter ( 5196):
I/flutter ( 5196): log:   libavcodec     62. 11.100 / 62. 11.100
I/flutter ( 5196):
I/flutter ( 5196): log:   libavformat    62.  3.100 / 62.  3.100
I/flutter ( 5196):
I/flutter ( 5196): log:   libavdevice    62.  1.100 / 62.  1.100
I/flutter ( 5196):
I/flutter ( 5196): log:   libavfilter    11.  4.100 / 11.  4.100
I/flutter ( 5196):
I/flutter ( 5196): log:   libswscale      9.  1.100 /  9.  1.100
I/flutter ( 5196):
I/flutter ( 5196): log:   libswresample   6.  1.100 /  6.  1.100
I/flutter ( 5196):
I/flutter ( 5196): log: Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/data/user/0/com.example.example/cache/sample_video.mp4':
I/flutter ( 5196):
I/flutter ( 5196): log:   Metadata:
I/flutter ( 5196):
I/flutter ( 5196): log:     major_brand     :
I/flutter ( 5196): log: isom
I/flutter ( 5196): log:
I/flutter ( 5196):
I/flutter ( 5196): log:     minor_version   :
I/flutter ( 5196): log: 512
I/flutter ( 5196): log:
I/flutter ( 5196):
I/flutter ( 5196): log:     compatible_brands:
I/flutter ( 5196): log: isomiso2avc1mp41
I/flutter ( 5196): log:
I/flutter ( 5196):
I/flutter ( 5196): log:     creation_time   :
I/flutter ( 5196): log: 1970-01-01T00:00:00.000000Z
I/flutter ( 5196): log:
I/flutter ( 5196):
I/flutter ( 5196): log:     encoder         :
I/flutter ( 5196): log: Lavf53.24.2
I/flutter ( 5196): log:
I/flutter ( 5196):
I/flutter ( 5196): log:   Duration:
I/flutter ( 5196): log: 00:00:13.70
I/flutter ( 5196): log: , start:
I/flutter ( 5196): log: 0.000000
I/flutter ( 5196): log: , bitrate:
I/flutter ( 5196): log: 615 kb/s
I/flutter ( 5196): log:
I/flutter ( 5196):
I/flutter ( 5196): log:   Stream #0
I/flutter ( 5196): log: :0
I/flutter ( 5196): log: [0x1]
I/flutter ( 5196): log: (und)
I/flutter ( 5196): log: : Video: h264 (avc1 / 0x31637661), yuv420p(progressive), 320x240 [SAR 1:1 DAR 4:3], 229 kb/s
I/flutter ( 5196): log: ,
I/flutter ( 5196): log: 15 fps,
I/flutter ( 5196): log: 15 tbr,
I/flutter ( 5196): log: 15360 tbn
I/flutter ( 5196): log:  (default)
I/flutter ( 5196): log:
I/flutter ( 5196):
I/flutter ( 5196): log:     Metadata:
I/flutter ( 5196):
I/flutter ( 5196): log:       creation_time   :
I/flutter ( 5196): log: 1970-01-01T00:00:00.000000Z
I/flutter ( 5196): log:
I/flutter ( 5196):
I/flutter ( 5196): log:       handler_name    :
I/flutter ( 5196): log: VideoHandler
I/flutter ( 5196): log:
I/flutter ( 5196):
I/flutter ( 5196): log:       vendor_id       :
I/flutter ( 5196): log: [0][0][0][0]
I/flutter ( 5196): log:
I/flutter ( 5196):
I/flutter ( 5196): log:   Stream #0
I/flutter ( 5196): log: :1
I/flutter ( 5196): log: [0x2]
I/flutter ( 5196): log: (und)
I/flutter ( 5196): log: : Audio: aac (mp4a / 0x6134706D), 48000 Hz, 5.1, fltp, 382 kb/s
I/flutter ( 5196): log:  (default)
I/flutter ( 5196): log:
I/flutter ( 5196):
I/flutter ( 5196): log:     Metadata:
I/flutter ( 5196):
I/flutter ( 5196): log:       creation_time   :
I/flutter ( 5196): log: 1970-01-01T00:00:00.000000Z
I/flutter ( 5196): log:
I/flutter ( 5196):
I/flutter ( 5196): log:       handler_name    :
I/flutter ( 5196): log: SoundHandler
I/flutter ( 5196): log:
I/flutter ( 5196):
I/flutter ( 5196): log:       vendor_id       :
I/flutter ( 5196): log: [0][0][0][0]
I/flutter ( 5196): log:
I/flutter ( 5196):
I/flutter ( 5196): log: Stream mapping:
I/flutter ( 5196):
I/flutter ( 5196): log:   Stream #0:0 -> #0:0
I/flutter ( 5196): log:  (h264 (native) -> h264 (h264_mediacodec))
I/flutter ( 5196): log:
I/flutter ( 5196):
I/flutter ( 5196): log:   Stream #0:1 -> #0:1
I/flutter ( 5196): log:  (aac (native) -> aac (native))
I/flutter ( 5196): log:
I/flutter ( 5196):
I/flutter ( 5196): log: Press [q] to stop, [?] for help
I/flutter ( 5196):
I/flutter ( 5196): log: [out_0_1 @ 0xb400007e76075570] Option 'all_channel_counts' is not a runtime option and so cannot be set after the object has been initialized
I/flutter ( 5196):
I/flutter ( 5196): log: Output pad "default" with type audio of the filter instance "Parsed_anull_0" of anull not connected to any destination
I/flutter ( 5196):
I/flutter ( 5196): log: Error reinitializing filters!
I/flutter ( 5196):
I/flutter ( 5196): log: Failed to inject frame into filter network: Invalid argument
I/flutter ( 5196):
I/flutter ( 5196): log: Error while processing the decoded data for stream #0:1
I/flutter ( 5196):
I/flutter ( 5196): log: Conversion failed!
I/flutter ( 5196):
I/flutter ( 5196): session: ffmpeg version n8.0 Copyright (c) 2000-2025 the FFmpeg developers
I/flutter ( 5196):   built with Android (13065274, +pgo, -bolt, +lto, -mlgo, based on r547379) clang version 20.0.0 (https://android.googlesource.com/toolchain/llvm-project b718bcaf8c198c82f3021447d943401e3ab5bd54)
I/flutter ( 5196):   configuration: --cross-prefix=aarch64-linux-android- --sysroot=/Users/me/Library/Android/sdk/ndk/29.0.13113456/toolchains/llvm/prebuilt/darwin-x86_64/sysroot --prefix=/Users/me/StudioProjects/ffmpeg-kit-6.0.LTS/prebuilt/android-arm64/ffmpeg --pkg-config=/opt/homebrew/bin/pkg-config --enable-version3 --arch=aarch64 --cpu=armv8-a --target-os=android --enable-neon --enable-asm --enable-inline-asm --ar=llvm-ar --cc=aarch64-linux-android24-clang --cxx=aarch64-linux-android24-clang++ --ranlib=llvm-ranlib --strip=llvm-strip --nm=llvm-nm --extra-libs='-L/Users/me/StudioProjects/ffmpeg-kit-6.0.LTS/prebuilt/android-arm64/cpu-features/lib -lndk_compat' --disable-autodetect --enable-cross-compile --enable-pic --enable-jni --enable-optimizations --enable-swscale --disable-static --enable-shared --enable-pthreads --enable-v4l2-m2m --disable-outdev=fbdev --disable-indev=fbdev --enable-small --disable-xmm-clobber-test --disable-debug --enable-lto --disable-neon-clobber-test --disable-programs --disable-doc --disable-htmlp
I/flutter ( 5196):   libavutil      60.  8.100 / 60.  8.100
I/flutter ( 5196):   libavcodec     62. 11.100 / 62. 11.100
I/flutter ( 5196):   libavformat    62.  3.100 / 62.  3.100
I/flutter ( 5196):   libavdevice    62.  1.100 / 62.  1.100
I/flutter ( 5196):   libavfilter    11.  4.100 / 11.  4.100
I/flutter ( 5196):   libswscale      9.  1.100 /  9.  1.100
I/flutter ( 5196):   libswresample   6.  1.100 /  6.  1.100
I/flutter ( 5196): Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/data/user/0/com.example.example/cache/sample_video.mp4':
I/flutter ( 5196):   Metadata:
I/flutter ( 5196):     major_brand     : isom
I/flutter ( 5196):     minor_version   : 512
I/flutter ( 5196):     compatible_brands: isomiso2avc1mp41
I/flutter ( 5196):     creation_time   : 1970-01-01T00:00:00.000000Z
I/flutter ( 5196):     encoder         : Lavf53.24.2
I/flutter ( 5196):   Duration: 00:00:13.70, start: 0.000000, bitrate: 615 kb/s
I/flutter ( 5196):   Stream #0:0[0x1](und): Video: h264 (avc1 / 0x31637661), yuv420p(progressive), 320x240 [SAR 1:1 DAR 4:3], 229 kb/s, 15 fps, 15 tbr, 15360 tbn (default)
I/flutter ( 5196):     Metadata:
I/flutter ( 5196):       creation_time   : 1970-01-01T00:00:00.000000Z
I/flutter ( 5196):       handler_name    : VideoHandler
I/flutter ( 5196):       vendor_id       : [0][0][0][0]
I/flutter ( 5196):   Stream #0:1[0x2](und): Audio: aac (mp4a / 0x6134706D), 48000 Hz, 5.1, fltp, 382 kb/s (default)
I/flutter ( 5196):     Metadata:
I/flutter ( 5196):       creation_time   : 1970-01-01T00:00:00.000000Z
I/flutter ( 5196):       handler_name    : SoundHandler
I/flutter ( 5196):       vendor_id       : [0][0][0][0]
I/flutter ( 5196): Stream mapping:
I/flutter ( 5196):   Stream #0:0 -> #0:0 (h264 (native) -> h264 (h264_mediacodec))
I/flutter ( 5196):   Stream #0:1 -> #0:1 (aac (native) -> aac (native))
I/flutter ( 5196): Press [q] to stop, [?] for help
I/flutter ( 5196): [out_0_1 @ 0xb400007e76075570] Option 'all_channel_counts' is not a runtime option and so cannot be set after the object has been initialized
I/flutter ( 5196): Output pad "default" with type audio of the filter instance "Parsed_anull_0" of anull not connected to any destination
I/flutter ( 5196): Error reinitializing filters!
I/flutter ( 5196): Failed to inject frame into filter network: Invalid argument
I/flutter ( 5196): Error while processing the decoded data for stream #0:1
I/flutter ( 5196): Conversion failed!
I/flutter ( 5196):

**Comment by sk3llo** [comment]
@rlueders thanks, good point. I found FFmpeg processing a bug in the recent `v8.0.0` and currently working on it.

**Comment by sk3llo** [comment]
@rlueders should be working as expected now

**Comment by rlueders** [comment]
Thanks. It looks like it is working on most devices/emulators now, but I still see the following error on my Pixel 10. Maybe this is a problem specific to just the Pixel 10. 


Resolving dependencies...
Downloading packages...
  characters 1.4.0 (1.4.1 available)
> ffmpeg_kit_flutter_new 4.1.0 from path .. (was 3.0.1 from path ..)
  flutter_lints 5.0.0 (6.0.0 available)
> leak_tracker 11.0.2 (was 10.0.9)
> leak_tracker_flutter_testing 3.0.10 (was 3.0.9)
> leak_tracker_testing 3.0.2 (was 3.0.1)
  lints 5.1.1 (6.0.0 available)
  material_color_utilities 0.11.1 (0.13.0 available)
  meta 1.16.0 (1.17.0 available)
  path_provider_android 2.2.17 (2.2.20 available)
  path_provider_foundation 2.4.1 (2.4.3 available)
> test_api 0.7.6 (was 0.7.4) (0.7.7 available)
> vector_math 2.2.0 (was 2.1.4)
  vm_service 15.0.0 (15.0.2 available)
Changed 6 dependencies!
9 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
Launching lib\main.dart on Pixel 10 in debug mode...
Warning: Flutter support for your project's Kotlin version (1.8.22) will soon be dropped. Please upgrade your Kotlin version to a version of at least 2.1.0 soon.
Alternatively, use the flag "--android-skip-build-dependency-validation" to bypass this check.

Potential fix: Your project's KGP version is typically defined in the plugins block of the `settings.gradle` file (C:\Projects\FFMPEG_KIT_NEW\ffmpeg_kit_flutter\example\android/settings.gradle), by a plugin with the id of org.jetbrains.kotlin.android.
If you don't see a plugins block, your project was likely created with an older template version, in which case it is most likely defined in the top-level build.gradle file (C:\Projects\FFMPEG_KIT_NEW\ffmpeg_kit_flutter\example\android/build.gradle) by the ext.kotlin_version property.

√ Built build\app\outputs\flutter-apk\app-debug.apk
Error: ADB exited with exit code 1
Performing Streamed Install

adb.exe: failed to install C:\Projects\FFMPEG_KIT_NEW\ffmpeg_kit_flutter\example\build\app\outputs\flutter-apk\app-debug.apk: Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Existing package com.example.example signatures do not match newer version; ignoring!]
Uninstalling old version...
D/FlutterJNI(15083): Beginning load of flutter...
D/FlutterJNI(15083): flutter (null) was loaded normally!
I/flutter (15083): [IMPORTANT:flutter/shell/platform/android/android_context_vk_impeller.cc(62)] Using the Impeller rendering backend (Vulkan).
I/flutter (15083): [IMPORTANT:flutter/shell/platform/android/android_context_gl_impeller.cc(104)] Using the Impeller rendering backend (OpenGLES).
Connecting to VM Service at ws://127.0.0.1:60757/iwmtTU5h6_8=/ws
Connected to the VM Service.
I/Choreographer(15083): Skipped 75 frames!  The application may be doing too much work on its main thread.
D/WindowLayoutComponentImpl(15083): Register WindowLayoutInfoListener on Context=com.example.example.MainActivity@a60ba72, of which baseContext=android.app.ContextImpl@8cb7d71
D/InsetsController(15083): hide(ime())
I/ImeTracker(15083): com.example.example:7bf8d45b: onCancelled at PHASE_CLIENT_ALREADY_HIDDEN
I/flutter (15083): Loading ffmpeg-kit-flutter.
I/flutter (15083): Loaded ffmpeg-kit-flutter-android-full-gpl-arm64-v8a-8.0.0.
I/flutter (15083): log: ffmpeg version n8.0
I/flutter (15083): log:  Copyright (c) 2000-2025 the FFmpeg developers
I/flutter (15083): log:
I/flutter (15083):
I/flutter (15083): log:   built with Android (13065274, +pgo, -bolt, +lto, -mlgo, based on r547379) clang version 20.0.0 (https://android.googlesource.com/toolchain/llvm-project b718bcaf8c198c82f3021447d943401e3ab5bd54)
I/flutter (15083):
I/flutter (15083): log:   configuration: --cross-prefix=aarch64-linux-android- --sysroot=/Users/me/Library/Android/sdk/ndk/29.0.13113456/toolchains/llvm/prebuilt/darwin-x86_64/sysroot --prefix=/Users/me/StudioProjects/ffmpeg-kit-6.0.LTS/prebuilt/android-arm64/ffmpeg --pkg-config=/opt/homebrew/bin/pkg-config --enable-version3 --arch=aarch64 --cpu=armv8-a --target-os=android --enable-neon --enable-asm --enable-inline-asm --ar=llvm-ar --cc=aarch64-linux-android24-clang --cxx=aarch64-linux-android24-clang++ --ranlib=llvm-ranlib --strip=llvm-strip --nm=llvm-nm --extra-libs='-L/Users/me/StudioProjects/ffmpeg-kit-6.0.LTS/prebuilt/android-arm64/cpu-features/lib -lndk_compat' --disable-autodetect --enable-cross-compile --enable-pic --enable-jni --enable-optimizations --enable-swscale --disable-static --enable-shared --enable-pthreads --enable-v4l2-m2m --disable-outdev=fbdev --disable-indev=fbdev --enable-small --disable-xmm-clobber-test --disable-debug --enable-lto --disable-neon-clobber-test --disable-programs --disable-doc --disable-
I/flutter (15083):
I/flutter (15083): log:   libavutil      60.  8.100 / 60.  8.100
I/flutter (15083):
I/flutter (15083): log:   libavcodec     62. 11.100 / 62. 11.100
I/flutter (15083):
I/flutter (15083): log:   libavformat    62.  3.100 / 62.  3.100
I/flutter (15083):
I/flutter (15083): log:   libavdevice    62.  1.100 / 62.  1.100
I/flutter (15083):
I/flutter (15083): log:   libavfilter    11.  4.100 / 11.  4.100
I/flutter (15083):
I/flutter (15083): log:   libswscale      9.  1.100 /  9.  1.100
I/flutter (15083):
I/flutter (15083): log:   libswresample   6.  1.100 /  6.  1.100
I/flutter (15083):
I/flutter (15083): log: Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/data/user/0/com.example.example/cache/sample_video.mp4':
I/flutter (15083):
I/flutter (15083): log:   Metadata:
I/flutter (15083):
I/flutter (15083): log:     major_brand     :
I/flutter (15083): log: isom
I/flutter (15083): log:
I/flutter (15083):
I/flutter (15083): log:     minor_version   :
I/flutter (15083): log: 512
I/flutter (15083): log:
I/flutter (15083):
I/flutter (15083): log:     compatible_brands:
I/flutter (15083): log: isomiso2avc1mp41
I/flutter (15083): log:
I/flutter (15083):
I/flutter (15083): log:     creation_time   :
I/flutter (15083): log: 1970-01-01T00:00:00.000000Z
I/flutter (15083): log:
I/flutter (15083):
I/flutter (15083): log:     encoder         :
I/flutter (15083): log: Lavf53.24.2
I/flutter (15083): log:
I/flutter (15083):
I/flutter (15083): log:   Duration:
I/flutter (15083): log: 00:00:13.70
I/flutter (15083): log: , start:
I/flutter (15083): log: 0.000000
I/flutter (15083): log: , bitrate:
I/flutter (15083): log: 615 kb/s
I/flutter (15083): log:
I/flutter (15083):
I/flutter (15083): log:   Stream #0
I/flutter (15083): log: :0
I/flutter (15083): log: [0x1]
I/flutter (15083): log: (und)
I/flutter (15083): log: : Video: h264 (avc1 / 0x31637661), yuv420p(progressive), 320x240 [SAR 1:1 DAR 4:3], 229 kb/s
I/flutter (15083): log: ,
I/flutter (15083): log: 15 fps,
I/flutter (15083): log: 15 tbr,
I/flutter (15083): log: 15360 tbn
I/flutter (15083): log:  (default)
I/flutter (15083): log:
I/flutter (15083):
I/flutter (15083): log:     Metadata:
I/flutter (15083):
I/flutter (15083): log:       creation_time   :
I/flutter (15083): log: 1970-01-01T00:00:00.000000Z
I/flutter (15083): log:
I/flutter (15083):
I/flutter (15083): log:       handler_name    :
I/flutter (15083): log: VideoHandler
I/flutter (15083): log:
I/flutter (15083):
I/flutter (15083): log:       vendor_id       :
I/flutter (15083): log: [0][0][0][0]
I/flutter (15083): log:
I/flutter (15083):
I/flutter (15083): log:   Stream #0
I/flutter (15083): log: :1
I/flutter (15083): log: [0x2]
I/flutter (15083): log: (und)
I/flutter (15083): log: : Audio: aac (mp4a / 0x6134706D), 48000 Hz, 5.1, fltp, 382 kb/s
I/flutter (15083): log:  (default)
I/flutter (15083): log:
I/flutter (15083):
I/flutter (15083): log:     Metadata:
I/flutter (15083):
I/flutter (15083): log:       creation_time   :
I/flutter (15083): log: 1970-01-01T00:00:00.000000Z
I/flutter (15083): log:
I/flutter (15083):
I/flutter (15083): log:       handler_name    :
I/flutter (15083): log: SoundHandler
I/flutter (15083): log:
I/flutter (15083):
I/flutter (15083): log:       vendor_id       :
I/flutter (15083): log: [0][0][0][0]
I/flutter (15083): log:
I/flutter (15083):
I/flutter (15083): log: Stream mapping:
I/flutter (15083):
I/flutter (15083): log:   Stream #0:0 -> #0:0
I/flutter (15083): log:  (h264 (native) -> h264 (h264_mediacodec))
I/flutter (15083): log:
I/flutter (15083):
I/flutter (15083): log:   Stream #0:1 -> #0:1
I/flutter (15083): log:  (aac (native) -> aac (native))
I/flutter (15083): log:
I/flutter (15083):
I/flutter (15083): log: Press [q] to stop, [?] for help
I/flutter (15083):
I/flutter (15083): log: [out_0_1 @ 0xb4000079fa6c54f0] The "all_channel_counts" option is deprecated: accept all channel counts
I/flutter (15083):
I/flutter (15083): log: [graph 0 input from stream 0:0 @ 0xb4000079fa6c6e50] Changing video frame properties on the fly is not supported by all filters.
I/flutter (15083):
I/flutter (15083): log: [graph 0 input from stream 0:0 @ 0xb4000079fa6c6e50] filter context - w: 320 h: 240 fmt: 0 csp: gbr range: unknown, incoming frame - w: 320 h: 240 fmt: 0 csp: unknown range: unknown pts_time: 0
I/flutter (15083):
D/MediaCodecList(15083): codecHandlesFormat: no format, so no extra checks
D/MediaCodecList(15083): codecHandlesFormat: no format, so no extra checks
D/CCodec  (15083): allocate(c2.google.avc.encoder)
I/ApexCodecsLazy(15083): ApexCodecs loaded
I/Codec2Client(15083): Available Codec2 services: "default" "default2" "software" "__ApexCodecs__"
I/CCodec  (15083): setting up 'default' as default (vendor) store
I/CCodec  (15083): Created component [c2.google.avc.encoder] for [c2.google.avc.encoder]
D/CCodecConfig(15083): read media type: video/avc
D/ReflectedParamUpdater(15083): extent() != 1 for single value type: input.buffers.allocator-ids.values
D/ReflectedParamUpdater(15083): extent() != 1 for single value type: output.buffers.allocator-ids.values
D/ReflectedParamUpdater(15083): extent() != 1 for single value type: output.buffers.pool-ids.values
D/ReflectedParamUpdater(15083): ignored struct field coding.gop.values
D/ReflectedParamUpdater(15083): extent() != 1 for single value type: output.subscribed-indices.values
D/ReflectedParamUpdater(15083): ignored struct field coding.qp.values
D/ReflectedParamUpdater(15083): ignored struct field resources.needed.values
D/CCodecConfig(15083): ignoring local param raw.color (0xc2001809) as it is already supported
I/CCodecConfig(15083): query failed after returning 20 values (BAD_INDEX)
D/CCodecConfig(15083): c2 config diff is Dict {
D/CCodecConfig(15083):   c2::u32 algo.bitrate-mode.value = 3
D/CCodecConfig(15083):   c2::u32 algo.encoding-quality-level.value = 0
D/CCodecConfig(15083):   c2::i32 algo.priority.value = 0
D/CCodecConfig(15083):   c2::float algo.rate.value = 0
D/CCodecConfig(15083):   c2::i32 coded.average-qp.value = 0
D/CCodecConfig(15083):   c2::u32 coded.bitrate.value = 64000
D/CCodecConfig(15083):   c2::float coded.frame-rate.value = 30
D/CCodecConfig(15083):   c2::u32 coded.hdr-format.value = 0
D/CCodecConfig(15083):   c2::u32 coded.picture-type.value = 0
D/CCodecConfig(15083):   c2::u32 coded.pl.level = 20483
D/CCodecConfig(15083):   c2::u32 coded.pl.profile = 20484
D/CCodecConfig(15083):   c2::u32 coding.request-sync-frame.value = 0
D/CCodecConfig(15083):   c2::i64 coding.sync-frame-interval.value = 1000000
D/CCodecConfig(15083):   c2::u32 input.delay.value = 0
D/CCodecConfig(15083):   Buffer input.hdr-dynamic-info.data = {
D/CCodecConfig(15083):   }
D/CCodecConfig(15083):   c2::u32 input.hdr-dynamic-info.type = 1
D/CCodecConfig(15083):   string input.media-type.value = "video/raw"
D/CCodecConfig(15083):   c2::float input.time-stretch.value = 1
D/CCodecConfig(15083):   c2::u32 output.buffers.prepend-header.value = 0
D/CCodecConfig(15083):   string output.media-type.value = "video/avc"
D/CCodecConfig(15083):   c2::u32 raw.color.matrix = 0
D/CCodecConfig(15083):   c2::u32 raw.color.primaries = 0
D/CCodecConfig(15083):   c2::u32 raw.color.range = 0
D/CCodecConfig(15083):   c2::u32 raw.color.transfer = 0
D/CCodecConfig(15083):   c2::float raw.hdr-static-info.mastering.blue.x = 0
D/CCodecConfig(15083):   c2
W/ColorUtils(15083): expected specified color aspects (0:0:0:0)
D/CCodecConfig(15083): found invalid HDR static metadata AMessage(what = 0x00000000) = {
D/CCodecConfig(15083):           int32_t android._color-format = 2130708361
D/CCodecConfig(15083):           float cta861.max-cll = 0.000000
D/CCodecConfig(15083):           float cta861.max-fall = 65536.000000
D/CCodecConfig(15083):           int32_t frame-rate = 30
D/CCodecConfig(15083):           int32_t height = 128
D/CCodecConfig(15083):           float input.time-stretch = 1.000000
D/CCodecConfig(15083):           string mime = "video/raw"
D/CCodecConfig(15083):           int32_t prepend-sps-pps-to-idr-frames = 0
D/CCodecConfig(15083):           int32_t priority = 0
D/CCodecConfig(15083):           float smpte2086.blue.x = 0.000000
D/CCodecConfig(15083):           float smpte2086.blue.y = 0.000000
D/CCodecConfig(15083):           float smpte2086.green.x = 0.000000
D/CCodecConfig(15083):           float smpte2086.green.y = 0.000000
D/CCodecConfig(15083):           float smpte2086.max-luminance = 0.000000
D/CCodecConfig(15083):           float smpte2086.min-luminance = 0.000000
D/CCodecConfig(15083):           float smpte2086.red.x = 0.000000
D/CCodecConfig(15083):           float smpte2086.red.y = 0.000000
D/CCodecConfig(15083):           float smpte2086.white.x = 0.000000
D/CCodecConfig(15083):           float smpte2086.white.y = 0.000000
D/CCodecConfig(15083):           int32_t video-qp-average = 0
D/CCodecConfig(15083):           int32_t width = 256
D/CCodecConfig(15083):           Rect crop(0, 0, 255, 127)
D/CCodecConfig(15083):           int32_t androi
I/MediaCodec(15083): media_quality service unavailable, skipping updatePictureProfile
I/flutter (15083): log: [h264_mediacodec @ 0xb4000079da857c00] Use 1 as the default MediaFormat i-frame-interval, please set gop_size properly (>= fps)
I/flutter (15083):
D/CodecSeeding(15083): Seed: codec c2.google.avc.encoder, mediatype video/avc, overrideable 1
D/CodecProperties(15083): setTuningValue(vq-target-bpp,0)
D/CodecProperties(15083): setTuningValue(vq-target-bpp-1080p,1.90)
D/CodecProperties(15083): setTuningValue(vq-target-bpp-720p,2.25)
D/CodecProperties(15083): setTuningValue(vq-target-bpp-540p,2.65)
D/CodecProperties(15083): setTuningValue(vq-target-bpp-480p,3.00)
D/CodecProperties(15083): setTuningValue(vq-target-bpp-320x240,0)
D/CodecProperties(15083): setTuningValue(vq-target-qpmax,-1)
D/CodecProperties(15083): setTuningValue(vq-target-qpmax-1080p,45)
D/CodecProperties(15083): setTuningValue(vq-target-qpmax-720p,43)
D/CodecProperties(15083): setTuningValue(vq-target-qpmax-540p,42)
D/CodecProperties(15083): setTuningValue(vq-target-qpmax-480p,38)
D/CodecProperties(15083): setTuningValue(vq-bitrate-phaseout,1.75)
D/CodecProperties(15083): setTuningValue(vq-boost-missing-qp,0.20)
D/CodecProperties(15083): setFeatureValue(can-swap-width-height,1)
D/CodecProperties(15083): setFeatureValue(encoding-statistics,0)
D/CodecProperties(15083): setFeatureValue(qp-bounds,0)
D/CodecProperties(15083): setFeatureValue(vq-minimum-quality,0)
D/CodecProperties(15083): setFeatureValue(_vq_eligible.device,1)
D/CodecProperties(15083): setFeatureValue(_quality.target,1)
D/CodecSeeding(15083): Seed: codec c2.google.avc.encoder, mediatype video/avc, overrideable 0
D/VQApply (15083): minquality: 320x240 outside of shaping range
D/MediaCodec(15083): shapeMediaFormat: deltas(1): AMessage(what = 0x00000000) = {
D/MediaCodec(15083):     int32_t android._encoding-quality-level = 0
D/MediaCodec(15083):   }
D/CCodec  (15083): [c2.google.avc.encoder] buffers are bound to CCodec for this session
D/CCodecConfig(15083): no c2 equivalents for color-format
D/CCodecConfig(15083): no c2 equivalents for flags
D/CCodecConfig(15083): no c2 equivalents for encoder
D/CCodecConfig(15083): c2 config diff is   c2::u32 coded.bitrate.value = 2000000
D/CCodecConfig(15083):   c2::float coded.frame-rate.value = 15
D/CCodecConfig(15083):   c2::u32 raw.pixel-format.value = 35
D/CCodecConfig(15083):   c2::u32 raw.size.height = 240
D/CCodecConfig(15083):   c2::u32 raw.size.width = 320
W/ColorUtils(15083): expected specified color aspects (0:0:0:0)
D/CCodecConfig(15083): found invalid HDR static metadata AMessage(what = 0x00000000) = {
D/CCodecConfig(15083):           int32_t android._color-format = 2135033992
D/CCodecConfig(15083):           float cta861.max-cll = 0.000000
D/CCodecConfig(15083):           float cta861.max-fall = 65536.000000
D/CCodecConfig(15083):           int32_t frame-rate = 15
D/CCodecConfig(15083):           int32_t height = 240
D/CCodecConfig(15083):           float input.time-stretch = 1.000000
D/CCodecConfig(15083):           string mime = "video/raw"
D/CCodecConfig(15083):           int32_t prepend-sps-pps-to-idr-frames = 0
D/CCodecConfig(15083):           int32_t priority = 0
D/CCodecConfig(15083):           float smpte2086.blue.x = 0.000000
D/CCodecConfig(15083):           float smpte2086.blue.y = 0.000000
D/CCodecConfig(15083):           float smpte2086.green.x = 0.000000
D/CCodecConfig(15083):           float smpte2086.green.y = 0.000000
D/CCodecConfig(15083):           float smpte2086.max-luminance = 0.000000
D/CCodecConfig(15083):           float smpte2086.min-luminance = 0.000000
D/CCodecConfig(15083):           float smpte2086.red.x = 0.000000
D/CCodecConfig(15083):           float smpte2086.red.y = 0.000000
D/CCodecConfig(15083):           float smpte2086.white.x = 0.000000
D/CCodecConfig(15083):           float smpte2086.white.y = 0.000000
D/CCodecConfig(15083):           int32_t video-qp-average = 0
D/CCodecConfig(15083):           int32_t width = 320
D/CCodecConfig(15083):           Rect crop(0, 0, 319, 239)
D/CCodecConfig(15083):           int32_t androi
D/AidlBufferPool(15083): Destruction - bufferpool2 0xb4000079aa691e88 cached: 0/0M, 0/0% in use; allocs: 1, 0% recycled; transfers: 0, 0% unfetched
D/CCodec  (15083): encoding statistics level = 0
D/CCodec  (15083): setup formats input: AMessage(what = 0x00000000) = {
D/CCodec  (15083):   int32_t android._color-format = 19
D/CCodec  (15083):   int32_t video-qp-average = 0
D/CCodec  (15083):   int32_t width = 320
D/CCodec  (15083):   int32_t frame-rate = 15
D/CCodec  (15083):   int32_t height = 240
D/CCodec  (15083):   float input.time-stretch = 1.000000
D/CCodec  (15083):   string mime = "video/raw"
D/CCodec  (15083):   int32_t prepend-sps-pps-to-idr-frames = 0
D/CCodec  (15083):   int32_t priority = 0
D/CCodec  (15083):   int32_t android._dataspace = 0
D/CCodec  (15083):   Rect crop(0, 0, 319, 239)
D/CCodec  (15083):   int64_t android._C2MemoryUsage = 65536
D/CCodec  (15083):   int32_t color-format = 19
D/CCodec  (15083):   int32_t stride = 320
D/CCodec  (15083):   int32_t slice-height = 240
D/CCodec  (15083): }
D/CCodec  (15083): setup formats output: AMessage(what = 0x00000000) = {
D/CCodec  (15083):   int32_t bitrate = 2000000
D/CCodec  (15083):   int32_t bitrate-mode = 1
D/CCodec  (15083):   Rect crop(0, 0, 319, 239)
D/CCodec  (15083):   int32_t color-standard = 0
D/CCodec  (15083):   int32_t color-range = 0
D/CCodec  (15083):   int32_t color-transfer = 0
D/CCodec  (15083):   int32_t frame-rate = 15
D/CCodec  (15083):   int32_t height = 240
D/CCodec  (15083):   float input.time-stretch = 1.000000
D/CCodec  (15083):   int32_t level = 8
D/CCodec  (15083):   int32_t max-bitrate = 2000000
D/CCodec  (15083):   string mime = "video/avc"
D/CCodec  (15083):   int32_t prepend-sps-pps-to-idr-frames = 0
D/CCodec  (15083):   int32_t priority = 0
D/CCodec  (15083):   int32_t profile = 8
D/CCodec  (15083):   int32_t video-qp-average = 0
D/CCodec  (15083):   int32_t width = 320
D/CCodec  (15083): }
I/CCodecConfig(15083): query failed after returning 21 values (BAD_INDEX)
D/CCodecConfig(15083): c2 config diff is   c2::u32 coded.pl.level = 20485
W/ColorUtils(15083): expected specified color aspects (0:0:0:0)
D/CCodecConfig(15083): found invalid HDR static metadata AMessage(what = 0x00000000) = {
D/CCodecConfig(15083):           int32_t android._color-format = 2135033992
D/CCodecConfig(15083):           float cta861.max-cll = 0.000000
D/CCodecConfig(15083):           float cta861.max-fall = 65536.000000
D/CCodecConfig(15083):           int32_t frame-rate = 15
D/CCodecConfig(15083):           int32_t height = 240
D/CCodecConfig(15083):           float input.time-stretch = 1.000000
D/CCodecConfig(15083):           string mime = "video/raw"
D/CCodecConfig(15083):           int32_t prepend-sps-pps-to-idr-frames = 0
D/CCodecConfig(15083):           int32_t priority = 0
D/CCodecConfig(15083):           float smpte2086.blue.x = 0.000000
D/CCodecConfig(15083):           float smpte2086.blue.y = 0.000000
D/CCodecConfig(15083):           float smpte2086.green.x = 0.000000
D/CCodecConfig(15083):           float smpte2086.green.y = 0.000000
D/CCodecConfig(15083):           float smpte2086.max-luminance = 0.000000
D/CCodecConfig(15083):           float smpte2086.min-luminance = 0.000000
D/CCodecConfig(15083):           float smpte2086.red.x = 0.000000
D/CCodecConfig(15083):           float smpte2086.red.y = 0.000000
D/CCodecConfig(15083):           float smpte2086.white.x = 0.000000
D/CCodecConfig(15083):           float smpte2086.white.y = 0.000000
D/CCodecConfig(15083):           int32_t video-qp-average = 0
D/CCodecConfig(15083):           int32_t width = 320
D/CCodecConfig(15083):           Rect crop(0, 0, 319, 239)
D/CCodecConfig(15083):           int32_t androi
D/CCodecBufferChannel(15083): [c2.google.avc.encoder#218] Created input block pool with allocatorID 17 => poolID 18 - OK (0)
D/C2Store (15083): Using DMABUF Heaps
I/CCodecBufferChannel(15083): [c2.google.avc.encoder#218] Created output block pool with allocatorID 16 => poolID 1913 - OK
D/CCodecBufferChannel(15083): [c2.google.avc.encoder#218] Configured output block pool ids 1913 => OK
D/CCodecBuffers(15083): [c2.google.avc.encoder#218:2D-BB-Input] updating image-data
D/CCodecBuffers(15083): [c2.google.avc.encoder#218:2D-BB-Input] updating stride = 320, width: 320, height: 240
D/CCodecBuffers(15083): [c2.google.avc.encoder#218:2D-BB-Input] updating vstride = 240
W/example.example(15083): AIBinder_linkToDeath is being called with a non-null cookie and no onUnlink callback set. This might not be intended. AIBinder_DeathRecipient_setOnUnlinked should be called first.
I/CCodecConfig(15083): query failed after returning 21 values (BAD_INDEX)
D/CCodecBufferChannel(15083): [c2.google.avc.encoder#218] work failed to complete: 95
E/MediaCodec(15083): Codec reported err 0x5f/95 (Unknown error -95), actionCode 0, while in state 6/STARTED
I/flutter (15083): log: Output #0, mp4, to '/data/user/0/com.example.example/cache/output.mp4':
I/flutter (15083):
I/flutter (15083): log:   Metadata:
I/flutter (15083):
I/flutter (15083): log:     major_brand     :
I/flutter (15083): log: isom
E/MediaCodec(15083): Invalid to call at Released state; only valid in executing state
I/flutter (15083): log:
I/flutter (15083):
I/flutter (15083): log:     minor_version   :
I/flutter (15083): log: 512
I/flutter (15083): log:
I/flutter (15083):
I/flutter (15083): log:     compatible_brands:
I/flutter (15083): log: isomiso2avc1mp41
I/flutter (15083): log:
I/flutter (15083):
I/flutter (15083): log:     encoder         :
I/flutter (15083): log: Lavf62.3.100
I/flutter (15083): log:
I/flutter (15083):
I/flutter (15083): log:   Stream #0
D/CCodecBufferChannel(15083): [c2.google.avc.encoder#218] MediaCodec discarded an unknown buffer
D/CCodecBufferChannel(15083): [c2.google.avc.encoder#218] MediaCodec discarded an unknown buffer
D/CCodecBufferChannel(15083): [c2.google.avc.encoder#218] MediaCodec discarded an unknown buffer
D/CCodecBufferChannel(15083): [c2.google.avc.encoder#218] MediaCodec discarded an unknown buffer
I/flutter (15083): log: :0
I/flutter (15083): log: (und)
I/flutter (15083): log: : Video: h264 (avc1 / 0x31637661), yuv420p(gbr/unknown/unknown, progressive), 320x240 [SAR 1:1 DAR 4:3], q=2-31, 2000 kb/s
I/flutter (15083): log: ,
I/flutter (15083): log: 15 fps,
I/flutter (15083): log: 15360 tbn
I/flutter (15083): log:  (default)
I/flutter (15083): log:
I/flutter (15083):
I/flutter (15083): log:     Metadata:
I/flutter (15083):
I/flutter (15083): log:       creation_time   :
I/flutter (15083): log: 1970-01-01T00:00:00.000000Z
I/flutter (15083): log:
I/flutter (15083):
I/flutter (15083): log:       handler_name    :
I/flutter (15083): log: VideoHandler
I/flutter (15083): log:
I/flutter (15083):
I/flutter (15083): log:       vendor_id       :
I/flutter (15083): log: [0][0][0][0]
I/flutter (15083): log:
I/flutter (15083):
I/flutter (15083): log:       encoder         :
I/flutter (15083): log: Lavc62.11.100 h264_mediacodec
I/flutter (15083): log:
I/flutter (15083):
I/flutter (15083): log:   Stream #0
I/flutter (15083): log: :1
I/flutter (15083): log: (und)
I/flutter (15083): log: : Audio: aac (mp4a / 0x6134706D), 48000 Hz, 5.1, fltp, 341 kb/s
I/flutter (15083): log:  (default)
I/flutter (15083): log:
I/flutter (15083):
I/flutter (15083): log:     Metadata:
I/flutter (15083):
I/flutter (15083): log:       creation_time   :
I/flutter (15083): log: 1970-01-01T00:00:00.000000Z
I/flutter (15083): log:
I/flutter (15083):
I/flutter (15083): log:       handler_name    :
I/flutter (15083): log: SoundHandler
I/flutter (15083): log:
I/flutter (15083):
I/flutter (15083): log:       vendor_id       :
I/flutter (15083): log: [0][0][0][0]
I/flutter (15083): log:
I/flutter (15083):
I/flutter (15083): log:       encoder         :
I/flutter (15083): log: Lavc62.11.100 aac
I/flutter (15083): log:
I/flutter (15083):
I/flutter (15083): log: [amediacodec @ 0xb4000079aa701760] java.lang.IllegalStateException: Invalid to call at Released state; only valid in executing state
I/flutter (15083): 
I/flutter (15083):
I/flutter (15083): log: [vost#0:0/h264_mediacodec @ 0xb4000078fa6e3310] Error submitting video frame to the encoder
I/flutter (15083):
I/flutter (15083): log: [amediacodec @ 0xb4000079aa701760] java.lang.IllegalStateException:
I/flutter (15083):
I/flutter (15083): log: [aac @ 0xb4000079da817100] Qavg: 4581.248
I/flutter (15083):
I/flutter (15083): log: [aac @ 0xb4000079da817100] 2 frames left in the queue on closing
I/flutter (15083):
I/flutter (15083): log: Conversion failed!
I/flutter (15083):
I/flutter (15083): session: ffmpeg version n8.0 Copyright (c) 2000-2025 the FFmpeg developers
I/flutter (15083):   built with Android (13065274, +pgo, -bolt, +lto, -mlgo, based on r547379) clang version 20.0.0 (https://android.googlesource.com/toolchain/llvm-project b718bcaf8c198c82f3021447d943401e3ab5bd54)
I/flutter (15083):   configuration: --cross-prefix=aarch64-linux-android- --sysroot=/Users/me/Library/Android/sdk/ndk/29.0.13113456/toolchains/llvm/prebuilt/darwin-x86_64/sysroot --prefix=/Users/me/StudioProjects/ffmpeg-kit-6.0.LTS/prebuilt/android-arm64/ffmpeg --pkg-config=/opt/homebrew/bin/pkg-config --enable-version3 --arch=aarch64 --cpu=armv8-a --target-os=android --enable-neon --enable-asm --enable-inline-asm --ar=llvm-ar --cc=aarch64-linux-android24-clang --cxx=aarch64-linux-android24-clang++ --ranlib=llvm-ranlib --strip=llvm-strip --nm=llvm-nm --extra-libs='-L/Users/me/StudioProjects/ffmpeg-kit-6.0.LTS/prebuilt/android-arm64/cpu-features/lib -lndk_compat' --disable-autodetect --enable-cross-compile --enable-pic --enable-jni --enable-optimizations --enable-swscale --disable-static --enable-shared --enable-pthreads --enable-v4l2-m2m --disable-outdev=fbdev --disable-indev=fbdev --enable-small --disable-xmm-clobber-test --disable-debug --enable-lto --disable-neon-clobber-test --disable-programs --disable-doc --disable-htmlp
I/flutter (15083):   libavutil      60.  8.100 / 60.  8.100
I/flutter (15083):   libavcodec     62. 11.100 / 62. 11.100
I/flutter (15083):   libavformat    62.  3.100 / 62.  3.100
I/flutter (15083):   libavdevice    62.  1.100 / 62.  1.100
I/flutter (15083):   libavfilter    11.  4.100 / 11.  4.100
I/flutter (15083):   libswscale      9.  1.100 /  9.  1.100
I/flutter (15083):   libswresample   6.  1.100 /  6.  1.100
I/flutter (15083): Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/data/user/0/com.example.example/cache/sample_video.mp4':
I/flutter (15083):   Metadata:
I/flutter (15083):     major_brand     : isom
I/flutter (15083):     minor_version   : 512
I/flutter (15083):     compatible_brands: isomiso2avc1mp41
I/flutter (15083):     creation_time   : 1970-01-01T00:00:00.000000Z
I/flutter (15083):     encoder         : Lavf53.24.2
I/flutter (15083):   Duration: 00:00:13.70, start: 0.000000, bitrate: 615 kb/s
I/flutter (15083):   Stream #0:0[0x1](und): Video: h264 (avc1 / 0x31637661), yuv420p(progressive), 320x240 [SAR 1:1 DAR 4:3], 229 kb/s, 15 fps, 15 tbr, 15360 tbn (default)
I/flutter (15083):     Metadata:
I/flutter (15083):       creation_time   : 1970-01-01T00:00:00.000000Z
I/flutter (15083):       handler_name    : VideoHandler
I/flutter (15083):       vendor_id       : [0][0][0][0]
I/flutter (15083):   Stream #0:1[0x2](und): Audio: aac (mp4a / 0x6134706D), 48000 Hz, 5.1, fltp, 382 kb/s (default)
I/flutter (15083):     Metadata:
I/flutter (15083):       creation_time   : 1970-01-01T00:00:00.000000Z
I/flutter (15083):       handler_name    : SoundHandler
I/flutter (15083):       vendor_id       : [0][0][0][0]
I/flutter (15083): Stream mapping:
I/flutter (15083):   Stream #0:0 -> #0:0 (h264 (native) -> h264 (h264_mediacodec))
I/flutter (15083):   Stream #0:1 -> #0:1 (aac (native) -> aac (native))
I/flutter (15083): Press [q] to stop, [?] for help
I/flutter (15083): [out_0_1 @ 0xb4000079fa6c54f0] The "all_channel_counts" option is deprecated: accept all channel counts
I/flutter (15083): [graph 0 input from stream 0:0 @ 0xb4000079fa6c6e50] Changing video frame properties on the fly is not supported by all filters.
I/flutter (15083): [graph 0 input from stream 0:0 @ 0xb4000079fa6c6e50] filter context - w: 320 h: 240 fmt: 0 csp: gbr range: unknown, incoming frame - w: 320 h: 240 fmt: 0 csp: unknown range: unknown pts_time: 0
I/flutter (15083): [h264_mediacodec @ 0xb4000079da857c00] Use 1 as the default MediaFormat i-frame-interval, please set gop_size properly (>= fps)
I/flutter (15083): Output #0, mp4, to '/data/user/0/com.example.example/cache/output.mp4':
I/flutter (15083):   Metadata:
I/flutter (15083):     major_brand     : isom
I/flutter (15083):     minor_version   : 512
I/flutter (15083):     compatible_brands: isomiso2avc1mp41
I/flutter (15083):     encoder         : Lavf62.3.100
I/flutter (15083):   Stream #0:0(und): Video: h264 (avc1 / 0x31637661), yuv420p(gbr/unknown/unknown, progressive), 320x240 [SAR 1:1 DAR 4:3], q=2-31, 2000 kb/s, 15 fps, 15360 tbn (default)
I/flutter (15083):     Metadata:
I/flutter (15083):       creation_time   : 1970-01-01T00:00:00.000000Z
I/flutter (15083):       handler_name    : VideoHandler
I/flutter (15083):       vendor_id       : [0][0][0][0]
I/flutter (15083):       encoder         : Lavc62.11.100 h264_mediacodec
I/flutter (15083):   Stream #0:1(und): Audio: aac (mp4a / 0x6134706D), 48000 Hz, 5.1, fltp, 341 kb/s (default)
I/flutter (15083):     Metadata:
I/flutter (15083):       creation_time   : 1970-01-01T00:00:00.000000Z
I/flutter (15083):       handler_name    : SoundHandler
I/flutter (15083):       vendor_id       : [0][0][0][0]
I/flutter (15083):       encoder         : Lavc62.11.100 aac
I/flutter (15083): [amediacodec @ 0xb4000079aa701760] java.lang.IllegalStateException: Invalid to call at Released state; only valid in executing state
I/flutter (15083):
I/flutter (15083): [vost#0:0/h264_mediacodec @ 0xb4000078fa6e3310] Error submitting video frame to the encoder
I/flutter (15083): [amediacodec @ 0xb4000079aa701760] java.lang.IllegalStateException:
I/flutter (15083): [aac @ 0xb4000079da817100] Qavg: 4581.248
I/flutter (15083): [aac @ 0xb4000079da817100] 2 frames left in the queue on closing
I/flutter (15083): Conversion failed!
I/flutter (15083):
D/ProfileInstaller(15083): Installing profile for com.example.example
D/AidlBufferPoolAcc(15083): evictor expired: 1, evicted: 0
W/example.example(15083): userfaultfd: MOVE ioctl seems unsupported: Connection timed out
D/AidlBufferPool(15083): bufferpool2 0xb4000079aa6cec18 : 0(0 size) total buffers - 0(0 size) used buffers - 65/70 (recycle/alloc) - 1/2 (fetch/transfer)
D/AidlBufferPoolAcc(15083): evictor expired: 1, evicted: 1

**Comment by theolm** [comment]
I'm having the same issue but only in release mode.
proguard is not enabled.

```sh
Caused by: java.lang.Error: FFmpegKit failed to start on brand: samsung, model: SM-S921B, device: e1s, api level: 36, abis: arm64-v8a, 32bit abis: , 64bit abis: arm64-v8a.
                                                                                                    	at e1.b.L(r8-map-id-987c43f3e848838d1ce8afad730d38760bad440ed0eb69223e80c7835b5c3339:110)
                                                                                                    	at com.antonkarpenko.ffmpegkit.AbiDetect.<clinit>(r8-map-id-987c43f3e848838d1ce8afad730d38760bad440ed0eb69223e80c7835b5c3339:3)
                                                                                                    	at com.antonkarpenko.ffmpegkit.FFmpegKitConfig.<clinit>(r8-map-id-987c43f3e848838d1ce8afad730d38760bad440ed0eb69223e80c7835b5c3339:16)
                                                                                                    	at K0.g.f(r8-map-id-987c43f3e848838d1ce8afad730d38760bad440ed0eb69223e80c7835b5c3339:20)
                                                                                                    	at O2.d.a(r8-map-id-987c43f3e848838d1ce8afad730d38760bad440ed0eb69223e80c7835b5c3339:119)
                                                                                                    	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(r8-map-id-987c43f3e848838d1ce8afad730d38760bad440ed0eb69223e80c7835b5c3339:44)
                                                                                                    	... 20 more
                                                                                                    Caused by: java.lang.UnsatisfiedLinkError: Bad JNI version returned from JNI_OnLoad in "/data/app/~~DU6INontaRY-HYZ7DV7_UA==/dev.theolm.trackie-20H5a38RA-OS-njRVMq6DQ==/base.apk!/lib/arm64-v8a/libffmpegkit_abidetect.so": 0
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1090)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1765)
                                                                                                    	at e1.b.L(r8-map-id-987c43f3e848838d1ce8afad730d38760bad440ed0eb69223e80c7835b5c3339:7)
```

**Comment by sk3llo** [comment]
Please check the latest version, it should be fixed there.
