### ISSUE TITLE
iOS app is not building with package

### ISSUE THREAD

**Issue by M-ImranNawaz** [sk3llo/ffmpeg_kit_flutter#7]
My app is not building with the following reason
following is the console output:

Launching lib/main.dart on iPhone 16 Plus in debug mode...
Xcode build done.                                           45.0s
Failed to build iOS app
Lexical or Preprocessor Issue (Xcode): 'ffmpegkit/FFmpegKitConfig.h' file not found
/Users/imrannawaz/.pub-cache/hosted/pub.dev/ffmpeg_kit_flutter_new-1.2.0/ios/Classes/FFmpegKitFlutterPlugin.m:21:8

Could not build the application for the simulator.
Error launching application on iPhone 16 Plus.

Exited (1).

**Comment by SameerDonga** [comment]
@M-ImranNawaz I was facing the same issue around 30 minutes ago.
How it resolved by me

1. Set iOS minimun version to 14
2. Update pod

**Comment by M-ImranNawaz** [comment]
@SameerDonga Still getting same issue check screenshot here:
https://snipboard.io/jqM8Dp.jpg

**Comment by elielnfinic** [comment]
Adding this too : 
```Synthetic package output (package:flutter_gen) is deprecated: https://flutter.dev/to/flutter-gen-deprecation. In a future release, synthetic-package will default to `false` and will later be removed entirely.
Launching lib/main.dart on iPhone 15 in debug mode...
Xcode build done.                                           290.9s
Failed to build iOS app
Error (Xcode): Building for 'iOS-simulator', but linking in dylib (/Users/username/.pub-cache/hosted/pub.dev/ffmpeg_kit_flutter_new-1.2.0/ios/Frameworks/ffmpegkit.framework/ffmpegkit) built for 'iOS'

Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)

Could not build the application for the simulator.
Error launching application on iPhone 15.```

I believe that something is wrong with the ffmpeg iOS build probably on ARM64.

**Comment by SameerDonga** [comment]
@elielnfinic & @elielnfinic

If possible, try to run the app on the real device (it works fine for me using a real device. Never tried with simulator)

**Comment by sk3llo** [comment]
@elielnfinic @M-ImranNawaz 

Are you able to run example project?

**Comment by M-ImranNawaz** [comment]
No @sk3llo, getting the same issue.

**Comment by sk3llo** [comment]
@M-ImranNawaz please try reinstalling PODS from scratch:

1. cd ios
2. rm -rf Pods
3. rm Podfile.lock
4. pod install --repo-update

If it still doesn't work, then it would be helpful if you can provide verbose log for `flutter build ios` command.

**Comment by DDANorthernSnakehead** [comment]
1) flutter pub remove ffmpeg_kit_flutter_new
2) flutter clean
3) cd ios && pod install && cd ..
4) ffmpeg_kit_flutter_new: 1.1.0 (not ffmpeg_kit_flutter_new: ^1.1.0)

I faced the same problem, and this is how I fixed it

**Comment by M-ImranNawaz** [comment]
@DDANorthernSnakehead still not working

**Comment by M-ImranNawaz** [comment]
@sk3llo still not working. following is the screenshot of error flutter build ios --verbose;

[https://snipboard.io/KOUSg5.jpg](url)

error text:

[  +11 ms] Failed to build iOS app
[  +28 ms] Lexical or Preprocessor Issue (Xcode): 'ffmpegkit/FFmpegKitConfig.h' file not found
           /Users/imrannawaz/.pub-cache/hosted/pub.dev/ffmpeg_kit_flutter_new-1.2.1/ios/Classes/FFmpegKitFlutterPlugin.m:21:8
           
[   +3 ms] "flutter ios" took 38,591ms.
[  +30 ms] Encountered error while building for device.
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:34:3)
           #1      _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:786:7)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1558:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:496:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:431:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:98:11)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:99:3)
           <asynchronous suspension>
           
           
[        ] Running 3 shutdown hooks
[   +1 ms] Shutdown hooks complete
[ +257 ms] exiting with code 1

**Comment by sk3llo** [comment]
@M-ImranNawaz I have tried multiple ways, but unable to reproduce the issue, so all further suggestions going to be blind shots that I think worth trying:

- First of all `flutter clean` the project, delete `Podfile.lock` and run `pod install`
- Run `pod update` to update pods to the latest configuration
- If something wrong with the downloaded library, then `flutter pub cache repair` might fix the issue

**Comment by sk3llo** [comment]
@bluej4ker https://github.com/sk3llo/ffmpeg_kit_flutter/issues/3#issuecomment-2837081984
